name: Deploying

on:
  push:
     branches: [ main ]
  pull_request:
     branches: [ main ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
 
      - name: Create EC2 and deploy application to EC2
        if: success()
        env: 
            KEY_PAIR_NAME: ${{ secrets.AWS_KEYPAIR_NAME }}
            SECGROUP_ID: ${{ secrets.AWS_SECGROUP_ID }}
        run: aws ec2 run-instances --image-id ami-04902260ca3d33422 --instance-type t2.micro  --key-name $KEY_PAIR_NAME --security-group-ids $SECGROUP_ID --user-data Deploy.sh 

